version: '3.3'

services:
    openjdk8:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: openjdk_8u131.11-r2
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.8
                - base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: openjdk8
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjdk_8u131.11-r2:${CONTAINER_TAG:-latest}
