version: '3.5'

services:
    openjdk:
        build:
            args:
                CONTAINER_NAME: openjdk_8u131.11-r2
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180303
            cache_from:
                - base_container:20180303
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        image: openjdk_8u131.11-r2:20180303
