version: '3.2'

services:
    openjdk:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
            context: .
        image: openjre_8u131.11-r2:20180210 
